### ISSUE TITLE
List of local variable names ending in semicolon leads to catastrophic backtracking error

### ISSUE THREAD

**Issue by e9gille** [Alhadis/language-apl#12]
Example line:
```apl
∇ Foo arg;local;
```
takes 562 steps according to [regex101](https://regex101.com/r/l0T4vu/1). For every character you increase the local name with, it seems to require twice as many steps.

By removing the `+` quantifier on line 666 it seems to fix the issue while still producing the expected result. I'm a novice in regex, so I'm not sure about the full impact of this change.

https://github.com/Alhadis/language-apl/blob/6f670b06418d265615e4d8679f4fbe343f6f417f/grammars/apl.cson#L654-L668

**Comment by e9gille** [comment]
As an example, this fails to render as APL:

```apl
∇ Foo arg;locallocallocallocal;
```

**Comment by Alhadis** [comment]
Hi @e9gille,

I'm aware of the performance issues with this particular expression. My knowledge of writing TextMate grammars was very minimal at the time I wrote this, and the pattern in question would need to be rewritten to be optimal (not an easy task).

Just curious, where/how did you experience a catastrophic backtracking error? Did you observe this in Atom, or somewhere else?

Moreover, both of the APL samples you've given me appear to be invalid syntax, at least in GNU APL:

~~~apl
∇ Foo arg;local1;local2;local3;
⎕←'Hi'
∇
~~~

~~~console
λ Desktop: apl --noSV -s -f test.apl
Offending token at UserFunction_header.cc:287 is: ;
DEFN ERROR+
      ∇ Foo arg;local1;local2;local3;
                                    ^
Hi
DEFN ERROR+
      ∇
      ^
~~~

Therefore, I surmise that a trailing semicolon should continue being highlighted as invalid.

**Comment by e9gille** [comment]
It was first reported by a VSCode user back in December, but I didn't know where to start in debugging the grammar. The symptom was that VSCode would freeze completely as soon as you tried to add a local variable by typing semicolon in the end of the first line (if it was sufficiently long to start with).

You are correct, it is invalid syntax if the line ends with a semicolon, and the grammar rightly marks it up as invalid. It just happens in the process of typing. As I say, even here in GitHub, if I extend your example with 2 more local variables, it fails to render it as invalid syntax for the local variables:

```apl
∇ Foo arg;local1;local2;local3;local4;local5;
⎕←'Hi'
∇
```

In actual fact, I believe the plus I suggest you remove is probably also behind the reason this line is considered valid when it shouldn't be (names must not be space separated):

```apl
∇ Foo arg;local variable
```

**Comment by Alhadis** [comment]
It'd be easier to just rewrite the pattern entirely, I think. Going by the number of capturing groups, there's about 30 distinct pattern-rules glued together and being matched simultaneously (for some reason… no idea what the hell I was thinking when I wrote this).

**Comment by kenmellem** [comment]
So the conclusion is what - that the syntax highlighting should (correctly) give the developer a hint that the code line is incorrect?
```apl
∇ Foo arg;local1;local2;
⎕←'Hi'
∇
```
vs correct
```apl
∇ Foo arg;local1;local2
⎕←'Hi'
∇
```

**Comment by Alhadis** [comment]
Kind of, yeah. I found these to be easy confusables:

~~~apl
∇R ← (LOP OPERATOR ROP) X ;A;B
	R ← X + Y
∇

⍝ Operator: Invalid
∇R ← X (LOP OPERATOR ROP) Y ;A;B;
	R ← X + Y
∇

∇R ← X (LOP OPERATOR ROP) Y Whoops;L;E;;;L
	R ← X + Y
∇

∇R ← X (LOP OPERATOR ROP) Y Whoops;k;e;k
	R ← X + Y
∇

∇R ← (LOP OPERATOR ROP) Y Invalid;B;R;U;H;
	R ← X + Y
∇

⍝ Axis operators
∇ FUNCTION [AXIS] right;X;Y
	⎕←input
∇

∇ left FUNCTION[AXIS INVALID] right
	⎕←input
∇

∇ Z ← X FUNCTION [ AXIS ] Y
	Z ← X + Y
∇
~~~

**Comment by Alhadis** [comment]
Okay, so, I can't rewrite the expression without losing a lot of accuracy (as well as our ability to highlight the function/operator's name in bold). Thankfully, a small fix to the capturing group that caused the performance drain appears to be working. @e9gille, could I get you to test the latest changes with your fork and confirm?

**Comment by e9gille** [comment]
Tested this and it fixes the "catastrophic backtracking" error. The other issue of space separated variable names is still not fixed. Would you like me to report that as a separate issue?

> In actual fact, I believe the plus I suggest you remove is probably also behind the reason this line is considered valid when it shouldn't be (names must not be space separated):
> 
> ```apl
> ∇ Foo arg;local variable
> ```

**Comment by Alhadis** [comment]
Oh, about that. Seems that [NARS2000 allows names](http://wiki.nars2000.org/index.php/User-Defined_Functions/Operators/Hyperators) to be separated either by space or semicolon:

> The local names to a user-defined function/operator/hyperator appear in the header to the right of the syntax part as above. The first local name is separated from the start of the header by a single semicolon; the second and subsequent local names are separated from each other by either a single semicolon or one or more blanks depending upon your own preference. For example
>
> ~~~apl
> ∇ Z←FOO R;g1 g2 g3 g4;h1 h2 h3
> ~~~

Hence why I've left it, and opted to use an atomic capturing group instead.

**Comment by e9gille** [comment]
I see, ok, nevermind then. I'll take on your changes.
