### ISSUE TITLE
Local variables on seperate line

### ISSUE THREAD

**Issue by kenmellem** [Alhadis/language-apl#13]
@Dyalog APL supports having local vars defined on other lines than the 0-line. 

```apl
∇ Foo arg
;local1;local2
⎕←'Hi'
∇
```
But this is rendered "incorrectly", i.e. it does not show these local vars as proper locally defined variables.

```apl
∇ Foo arg;local1;local2
⎕←'Hi'
∇
```

Is this something we could have incorporated?

**Comment by Alhadis** [comment]
Yes. Must the local-variable line immediately precede the 0-line, or can it be placed anywhere in the function body? Or should I ask, are these constructs both valid too?

~~~apl
∇ Foo arg
⎕←'Hi'
;local1;local2
∇
~~~

~~~apl
∇ Foo arg
;local2
⎕←'Hi'
;local1
∇
~~~

**Comment by kenmellem** [comment]
I copied from help.dyalog.com

> A Locals Line may appear anywhere between line [0] and the first executable statement in the function or operator. Locals lines may be interspersed with blank lines and comments. A Locals Line is identified by starting with a semicolon, prefixed optionally by whitespace. It may contain a comment at the end.
> 
> A Locals Line must be of the form ;name;name;name where name is any valid APL name or localisable system variable. The names are localised on entry to the function exactly as if they were specified as locals on line [0].
>
> Example
```
       ∇ r←foo y;a;b       ⍝ some locals
                ;c;d       ⍝ some more locals  
         (a b c d)←y
         r←a+b-c×d 
       ∇
```

**Comment by kenmellem** [comment]
The restriction with "first executable statement" might really not be necessary - but it sure helps our internal static APL parser quite a bit as it cannot possibly evaluate jumps and goto's. ;)

**Comment by Alhadis** [comment]
Gotcha. 😉

I'm currently setting up a test-harness so any undesirable changes resulting from a rewrite for #12 will be noticed. I'll action this fix while I'm there, since it's the same code.
