### ISSUE TITLE
Tally does not render correctly (match+stile)

### ISSUE THREAD

**Issue by kenmellem** [Alhadis/language-apl#14]
The **tally** function which is a combination of match (≡) and slash(/) does not correctly render (≢)  as the combined character (similar to not-equal (≠)).

```apl
∇ tallyShownAsTwoChars
≢
∇
```

Sorry if this Issue should be reported elsewhere.
Note: this is what is happening on my computer - and everyone in my company using Github Enterprise using Windows. Have not tested on Mac.

**Comment by e9gille** [comment]
This is a known bug on Windows. It's been reported by ~~Nick Nikolov~~ Adam Brudz somewhere (I'll se if I can find the link). Nothing you can do about it here I'm afraid.

**Comment by Alhadis** [comment]
That has nothing to do with either of us, and everything to do with the design of that particular glyph in the font GitHub's using for character rendering. I'm seeing it too; note that when inspected in the devtools, the highlighted character appears as one glyph:

<img src="https://user-images.githubusercontent.com/2346707/57157704-d13fad00-6e24-11e9-9397-43cfb449949b.png"  alt="Figure 1" />

Which, on this current machine (macOS), is [Consolas](https://en.wikipedia.org/wiki/Consolas).

**Comment by e9gille** [comment]
here, found it:
https://bugs.chromium.org/p/chromium/issues/detail?id=620629#c8
and it's been closed as you can see...

**Comment by Alhadis** [comment]
Yeah, I suspected it had something to do with font-rendering, which may have actually been a conscious decision from a Chromium developer.

BTW, if you observed a `=` and `/` character merging in two different keystrokes, it's possible the editor font is using an OpenType contextual ligature to make two adjacent characters appear to be a single entity.

Ligatures are fun to play with, and I've actually edited my preferred font with "elastic" versions of `←` that expand to fill surrounding space:
![figure-2](https://user-images.githubusercontent.com/2346707/57158251-511a4700-6e26-11e9-971a-d900a46ef0b7.png)

Look what happens when I remove the spaces:
~~~apl
|not P|  |ntP|
|\ & ¯|  |\&¯|
|≡ ≢ ≤|  |≡≢≤|
~~~

![figure-1](https://user-images.githubusercontent.com/2346707/57158659-5035e500-6e27-11e9-87d0-d1beddf25722.png)

A similar effect is being achieved with these sequences:
~~~javascript
/= ==
=> <=
-> <-
~~~
<img src="https://user-images.githubusercontent.com/2346707/57158839-bf133e00-6e27-11e9-8f89-440f223c4176.png" />

**Comment by e9gille** [comment]
That's really interesting. We've talked about (and tried) coding with a proportionate font, but I haven't got used to coding in anything but a monospaced font. The argument was to use a non-mono font in the context of articles, academic papers or the like to make it fit in with the text.

**Comment by Alhadis** [comment]
I'm a HUGE font/typography nerd. You've come to the right place.

My favourite font for technical documentation is [Cambria Math](https://docs.microsoft.com/en-us/typography/font-list/cambria-math) (commercial, but available on all Windows systems). I could easily enhance it for you in an editor if you needed clearer-looking APL glyphs.

**Comment by kenmellem** [comment]
What about the font Dyalog has - [APL385](https://www.dyalog.com/apl-font-keyboard.htm)?
Could it be an alternative to set this as default for *.apl code?

**Comment by e9gille** [comment]
I'll check out the Cambria Math font, but it would be good to have a font that could be generally distributed.

I don't know that you can specify a font to be used on GitHub, can you?

**Comment by kenmellem** [comment]
> I don't know that you can specify a font to be used on GitHub, can you?

https://stackoverflow.com/questions/7372428/changing-the-default-github-code-font
which of course is not an optimal solution... it is also 3 years old.

**Comment by Alhadis** [comment]
Nope, sorry. Design-related facets (like font choices) are entirely internal to GitHub's design team. This is the monospace font-stack being used in the site's CSS:

~~~css
code, pre, tt {
	font-family: SFMono-Regular, Consolas ,Liberation Mono, Menlo, Courier, monospace;
}
~~~

Browsers use the first font-face they have available, so the exact font you see depends on what fonts you have installed on your system. Good news, though: if you install Chrome's [User CSS extension](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb), you can forcefully change the APL font by adding this snippet of CSS:

~~~css
pre.highlight-source-apl,
code.highlight-source-apl,
.highlight-source-apl pre,
.highlight-source-apl code{
	font-family: APL385;
}
~~~

**Comment by kenmellem** [comment]
I opened up this issue on my Mac - using Safari - and it renders the glyph correctly. As also proven on the chromium ticket by some user. How can the conclusion on that ticket be correct?

**Comment by e9gille** [comment]
Interesting, on my Chrome on Mac it rendered tally correctly in Menlo.

Cambria Math tested on RIDE. APL glyphs would definitely need some work:

![image](https://user-images.githubusercontent.com/8232484/57160963-a0db1d00-6dea-11e9-816b-7da4ff64f583.png)

**Comment by Alhadis** [comment]
Are you intending to use a proportional font for editing or printing/publication? If it's the former, you won't find too many that look good in a code editor...

[Here's my patched editor-font](https://github.com/Alhadis/.files/blob/master/share/desktop/Menlig.otf), BTW. In case you were curious (I added and tweaked the APL glyphs myself, IIRC).

**Comment by e9gille** [comment]
Well, we've explored using it for editing but I find it distracting when things don't line up :)
I've tested you font briefly, will try using it while working and will let you know. Looks nice though on first glance.

**Comment by Alhadis** [comment]
I'm assuming Dyalog's text editing windows don't support OpenType features like ligatures and contextual alternates. Mine does. 😂

Being able to type `->` and have it look like an actual arrow is something you tend to miss when it's gone.

**Comment by Alhadis** [comment]
Anywayyyyyy. The original issue is not only unrelated to this package or GitHub, but something that's completely out of our power. So I'm gonna close this issue: I recommend opening a new ticket to Chromium, and hopefully you get some cold hard rationale WHY "strictly not equal to" is displayed as "equal forward slash".
